{
	"_dispatchInstances": {
		"_debugHookTypes": null,
		"_debugID": 17,
		"_debugIsCurrentlyTiming": false,
		"_debugNeedsRemount": false,
		"_debugOwner": {
			"_debugHookTypes": null,
			"_debugID": 15,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": null,
			"_debugSource": [Object],
			"actualDuration": 116,
			"actualStartTime": 1201308,
			"alternate": [FiberNode],
			"child": [Circular],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 1,
			"elementType": [Function App],
			"expirationTime": 0,
			"firstEffect": [FiberNode],
			"index": 0,
			"key": null,
			"lastEffect": [FiberNode],
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 5,
			"sibling": null,
			"stateNode": null,
			"tag": 0,
			"treeBaseDuration": 116,
			"type": [Function App],
			"updateQueue": null
		},
		"_debugSource": {
			"columnNumber": 5,
			"fileName": "/home/shubham/react/hello/App.js",
			"lineNumber": 42
		},
		"actualDuration": 103,
		"actualStartTime": 1201313,
		"alternate": {
			"_debugHookTypes": null,
			"_debugID": 17,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 0,
			"actualStartTime": 3162,
			"alternate": [Circular],
			"child": [FiberNode],
			"childExpirationTime": 1073741823,
			"dependencies": null,
			"effectTag": 0,
			"elementType": "RCTView",
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 0,
			"sibling": [FiberNode],
			"stateNode": [ReactNativeFiberHostComponent],
			"tag": 5,
			"treeBaseDuration": 64,
			"type": "RCTView",
			"updateQueue": null
		},
		"child": {
			"_debugHookTypes": null,
			"_debugID": 20,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 0,
			"actualStartTime": 1201314,
			"alternate": [FiberNode],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 1,
			"elementType": [Object],
			"expirationTime": 0,
			"firstEffect": [FiberNode],
			"index": 0,
			"key": null,
			"lastEffect": [FiberNode],
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [Circular],
			"selfBaseDuration": 0,
			"sibling": [FiberNode],
			"stateNode": null,
			"tag": 11,
			"treeBaseDuration": 0,
			"type": [Object],
			"updateQueue": null
		},
		"childExpirationTime": 0,
		"dependencies": null,
		"effectTag": 4,
		"elementType": "RCTView",
		"expirationTime": 0,
		"firstEffect": {
			"_debugHookTypes": null,
			"_debugID": 29,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 0,
			"actualStartTime": 1201315,
			"alternate": [FiberNode],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 4,
			"elementType": "RCTText",
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 0,
			"sibling": null,
			"stateNode": [ReactNativeFiberHostComponent],
			"tag": 5,
			"treeBaseDuration": 0,
			"type": "RCTText",
			"updateQueue": null
		},
		"index": 0,
		"key": null,
		"lastEffect": {
			"_debugHookTypes": [Array],
			"_debugID": 21,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 102,
			"actualStartTime": 1201315,
			"alternate": [FiberNode],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 517,
			"elementType": [Object],
			"expirationTime": 0,
			"firstEffect": [FiberNode],
			"index": 1,
			"key": null,
			"lastEffect": [FiberNode],
			"memoizedProps": [Object],
			"memoizedState": [Object],
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [Circular],
			"selfBaseDuration": 0,
			"sibling": null,
			"stateNode": null,
			"tag": 11,
			"treeBaseDuration": 102,
			"type": [Object],
			"updateQueue": [Object]
		},
		"memoizedProps": {
			"children": [Array],
			"onTouchStart": [Function onTouchStart]
		},
		"memoizedState": null,
		"mode": 8,
		"nextEffect": null,
		"pendingProps": {
			"children": [Array],
			"onTouchStart": [Function onTouchStart]
		},
		"ref": null,
		"return": {
			"_debugHookTypes": null,
			"_debugID": 15,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": null,
			"_debugSource": [Object],
			"actualDuration": 116,
			"actualStartTime": 1201308,
			"alternate": [FiberNode],
			"child": [Circular],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 1,
			"elementType": [Function App],
			"expirationTime": 0,
			"firstEffect": [FiberNode],
			"index": 0,
			"key": null,
			"lastEffect": [FiberNode],
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 5,
			"sibling": null,
			"stateNode": null,
			"tag": 0,
			"treeBaseDuration": 116,
			"type": [Function App],
			"updateQueue": null
		},
		"selfBaseDuration": 1,
		"sibling": {
			"_debugHookTypes": null,
			"_debugID": 18,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 8,
			"actualStartTime": 1201418,
			"alternate": [FiberNode],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 129,
			"elementType": [Function Fiboview],
			"expirationTime": 0,
			"firstEffect": [FiberNode],
			"index": 1,
			"key": null,
			"lastEffect": [FiberNode],
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": [Function ref],
			"return": [FiberNode],
			"selfBaseDuration": 7,
			"sibling": null,
			"stateNode": [Fiboview],
			"tag": 1,
			"treeBaseDuration": 8,
			"type": [Function Fiboview],
			"updateQueue": null
		},
		"stateNode": {
			"_children": [Array],
			"_nativeTag": 79,
			"viewConfig": [Object]
		},
		"tag": 5,
		"treeBaseDuration": 103,
		"type": "RCTView",
		"updateQueue": null
	},
	"_dispatchListeners": [Function onTouchStart],
	"_targetInst": {
		"_debugHookTypes": null,
		"_debugID": 29,
		"_debugIsCurrentlyTiming": false,
		"_debugNeedsRemount": false,
		"_debugOwner": {
			"_debugHookTypes": null,
			"_debugID": 25,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 7,
			"actualStartTime": 288,
			"alternate": [FiberNode],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": [Object],
			"effectTag": 1,
			"elementType": [Object],
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 1,
			"sibling": null,
			"stateNode": null,
			"tag": 9,
			"treeBaseDuration": 1,
			"type": [Object],
			"updateQueue": null
		},
		"_debugSource": {
			"columnNumber": 15,
			"fileName": "/home/shubham/react/hello/node_modules/react-native/Libraries/Text/Text.js",
			"lineNumber": 159
		},
		"actualDuration": 6,
		"actualStartTime": 289,
		"alternate": {
			"_debugHookTypes": null,
			"_debugID": 29,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 0,
			"actualStartTime": 1201315,
			"alternate": [Circular],
			"child": [FiberNode],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 4,
			"elementType": "RCTText",
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 0,
			"sibling": null,
			"stateNode": [ReactNativeFiberHostComponent],
			"tag": 5,
			"treeBaseDuration": 0,
			"type": "RCTText",
			"updateQueue": null
		},
		"child": {
			"_debugHookTypes": null,
			"_debugID": 31,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": null,
			"_debugSource": null,
			"actualDuration": 3,
			"actualStartTime": 289,
			"alternate": [FiberNode],
			"child": null,
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 0,
			"elementType": null,
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": "Hello world",
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": "Hello world",
			"ref": null,
			"return": [Circular],
			"selfBaseDuration": 0,
			"sibling": null,
			"stateNode": 3,
			"tag": 6,
			"treeBaseDuration": 0,
			"type": null,
			"updateQueue": null
		},
		"childExpirationTime": 0,
		"dependencies": null,
		"effectTag": 0,
		"elementType": "RCTText",
		"expirationTime": 0,
		"firstEffect": null,
		"index": 0,
		"key": null,
		"lastEffect": null,
		"memoizedProps": {
			"accessible": true,
			"allowFontScaling": true,
			"children": "Hello world",
			"ellipsizeMode": "tail",
			"forwardedRef": null
		},
		"memoizedState": null,
		"mode": 8,
		"nextEffect": null,
		"pendingProps": {
			"accessible": true,
			"allowFontScaling": true,
			"children": "Hello world",
			"ellipsizeMode": "tail",
			"forwardedRef": null
		},
		"ref": null,
		"return": {
			"_debugHookTypes": null,
			"_debugID": 27,
			"_debugIsCurrentlyTiming": false,
			"_debugNeedsRemount": false,
			"_debugOwner": [FiberNode],
			"_debugSource": [Object],
			"actualDuration": 6,
			"actualStartTime": 289,
			"alternate": [FiberNode],
			"child": [Circular],
			"childExpirationTime": 0,
			"dependencies": null,
			"effectTag": 0,
			"elementType": [Object],
			"expirationTime": 0,
			"firstEffect": null,
			"index": 0,
			"key": null,
			"lastEffect": null,
			"memoizedProps": [Object],
			"memoizedState": null,
			"mode": 8,
			"nextEffect": null,
			"pendingProps": [Object],
			"ref": null,
			"return": [FiberNode],
			"selfBaseDuration": 0,
			"sibling": null,
			"stateNode": null,
			"tag": 10,
			"treeBaseDuration": 0,
			"type": [Object],
			"updateQueue": null
		},
		"selfBaseDuration": 0,
		"sibling": null,
		"stateNode": {
			"_children": [Array],
			"_nativeTag": 5,
			"viewConfig": [Object]
		},
		"tag": 5,
		"treeBaseDuration": 0,
		"type": "RCTText",
		"updateQueue": null
	},
	"bubbles": undefined,
	"cancelable": undefined,
	"currentTarget": 79,
	"defaultPrevented": undefined,
	"dispatchConfig": {
		"phasedRegistrationNames": {
			"bubbled": "onTouchStart",
			"captured": "onTouchStartCapture"
		}
	},
	"eventPhase": undefined,
	"isDefaultPrevented": [Function functionThatReturnsFalse],
	"isPropagationStopped": [Function functionThatReturnsFalse],
	"isTrusted": undefined,
	"nativeEvent": {
		"changedTouches": [
			[Circular]
		],
		"identifier": 0,
		"locationX": 52.66666793823242,
		"locationY": 10.333333015441895,
		"pageX": 52.66666793823242,
		"pageY": 10.333333015441895,
		"target": 5,
		"timestamp": 413207051,
		"touches": [
			[Circular]
		]
	},
	"target": 5,
	"timeStamp": 1598349297801,
	"type": undefined
}

/*******************************************************************************************************/

{
	"uiViewClassName": "RCTView",
	"Commands": {},
	"bubblingEventTypes": {
		"topSelect": {
			"phasedRegistrationNames": {
				"bubbled": "onSelect",
				"captured": "onSelectCapture"
			}
		},
		"topBlur": {
			"phasedRegistrationNames": {
				"bubbled": "onBlur",
				"captured": "onBlurCapture"
			}
		},
		"topChange": {
			"phasedRegistrationNames": {
				"bubbled": "onChange",
				"captured": "onChangeCapture"
			}
		},
		"topEndEditing": {
			"phasedRegistrationNames": {
				"bubbled": "onEndEditing",
				"captured": "onEndEditingCapture"
			}
		},
		"topFocus": {
			"phasedRegistrationNames": {
				"bubbled": "onFocus",
				"captured": "onFocusCapture"
			}
		},
		"topKeyPress": {
			"phasedRegistrationNames": {
				"bubbled": "onKeyPress",
				"captured": "onKeyPressCapture"
			}
		},
		"topPress": {
			"phasedRegistrationNames": {
				"bubbled": "onPress",
				"captured": "onPressCapture"
			}
		},
		"topSubmitEditing": {
			"phasedRegistrationNames": {
				"bubbled": "onSubmitEditing",
				"captured": "onSubmitEditingCapture"
			}
		},
		"topTouchCancel": {
			"phasedRegistrationNames": {
				"bubbled": "onTouchCancel",
				"captured": "onTouchCancelCapture"
			}
		},
		"topTouchEnd": {
			"phasedRegistrationNames": {
				"bubbled": "onTouchEnd",
				"captured": "onTouchEndCapture"
			}
		},
		"topTouchMove": {
			"phasedRegistrationNames": {
				"bubbled": "onTouchMove",
				"captured": "onTouchMoveCapture"
			}
		},
		"topTouchStart": {
			"phasedRegistrationNames": {
				"bubbled": "onTouchStart",
				"captured": "onTouchStartCapture"
			}
		}
	},
	"directEventTypes": {
		"topClick": {
			"registrationName": "onClick"
		},
		"topContentSizeChange": {
			"registrationName": "onContentSizeChange"
		},
		"topLoadingError": {
			"registrationName": "onLoadingError"
		},
		"topLoadingFinish": {
			"registrationName": "onLoadingFinish"
		},
		"topLoadingStart": {
			"registrationName": "onLoadingStart"
		},
		"topMessage": {
			"registrationName": "onMessage"
		},
		"topMomentumScrollBegin": {
			"registrationName": "onMomentumScrollBegin"
		},
		"topMomentumScrollEnd": {
			"registrationName": "onMomentumScrollEnd"
		},
		"topScroll": {
			"registrationName": "onScroll"
		},
		"topScrollBeginDrag": {
			"registrationName": "onScrollBeginDrag"
		},
		"topScrollEndDrag": {
			"registrationName": "onScrollEndDrag"
		},
		"topSelectionChange": {
			"registrationName": "onSelectionChange"
		},
		"topAccessibilityAction": {
			"registrationName": "onAccessibilityAction"
		},
		"topAccessibilityEscape": {
			"registrationName": "onAccessibilityEscape"
		},
		"topAccessibilityTap": {
			"registrationName": "onAccessibilityTap"
		},
		"topLayout": {
			"registrationName": "onLayout"
		},
		"topMagicTap": {
			"registrationName": "onMagicTap"
		},
		"onGestureHandlerEvent": {
			"registrationName": "onGestureHandlerEvent"
		},
		"onGestureHandlerStateChange": {
			"registrationName": "onGestureHandlerStateChange"
		}
	},
	"validAttributes": {
		"hasTVPreferredFocus": true,
		"focusable": true,
		"nativeBackgroundAndroid": true,
		"nativeForegroundAndroid": true,
		"nextFocusDown": true,
		"nextFocusForward": true,
		"nextFocusLeft": true,
		"nextFocusRight": true,
		"nextFocusUp": true,
		"accessibilityActions": true,
		"accessibilityElementsHidden": true,
		"accessibilityHint": true,
		"accessibilityIgnoresInvertColors": true,
		"accessibilityLabel": true,
		"accessibilityLiveRegion": true,
		"accessibilityRole": true,
		"accessibilityStates": true,
		"accessibilityState": true,
		"accessibilityValue": true,
		"accessibilityViewIsModal": true,
		"accessible": true,
		"alignContent": true,
		"alignItems": true,
		"alignSelf": true,
		"aspectRatio": true,
		"backfaceVisibility": true,
		"backgroundColor": {},
		"borderBottomColor": {},
		"borderBottomEndRadius": true,
		"borderBottomLeftRadius": true,
		"borderBottomRightRadius": true,
		"borderBottomStartRadius": true,
		"borderBottomWidth": true,
		"borderColor": {},
		"borderEndColor": {},
		"borderEndWidth": true,
		"borderLeftColor": {},
		"borderLeftWidth": true,
		"borderRadius": true,
		"borderRightColor": {},
		"borderRightWidth": true,
		"borderStartColor": {},
		"borderStartWidth": true,
		"borderStyle": true,
		"borderTopColor": {},
		"borderTopEndRadius": true,
		"borderTopLeftRadius": true,
		"borderTopRightRadius": true,
		"borderTopStartRadius": true,
		"borderTopWidth": true,
		"borderWidth": true,
		"bottom": true,
		"clickable": true,
		"collapsable": true,
		"direction": true,
		"display": true,
		"elevation": true,
		"end": true,
		"flex": true,
		"flexBasis": true,
		"flexDirection": true,
		"flexGrow": true,
		"flexShrink": true,
		"flexWrap": true,
		"height": true,
		"hitSlop": {},
		"importantForAccessibility": true,
		"justifyContent": true,
		"left": true,
		"margin": true,
		"marginBottom": true,
		"marginEnd": true,
		"marginHorizontal": true,
		"marginLeft": true,
		"marginRight": true,
		"marginStart": true,
		"marginTop": true,
		"marginVertical": true,
		"maxHeight": true,
		"maxWidth": true,
		"minHeight": true,
		"minWidth": true,
		"nativeID": true,
		"needsOffscreenAlphaCompositing": true,
		"onAccessibilityAction": true,
		"onAccessibilityEscape": true,
		"onAccessibilityTap": true,
		"onLayout": true,
		"onMagicTap": true,
		"opacity": true,
		"overflow": true,
		"padding": true,
		"paddingBottom": true,
		"paddingEnd": true,
		"paddingHorizontal": true,
		"paddingLeft": true,
		"paddingRight": true,
		"paddingStart": true,
		"paddingTop": true,
		"paddingVertical": true,
		"pointerEvents": true,
		"position": true,
		"removeClippedSubviews": true,
		"renderToHardwareTextureAndroid": true,
		"right": true,
		"rotation": true,
		"scaleX": true,
		"scaleY": true,
		"shadowColor": {},
		"shadowOffset": {},
		"shadowOpacity": true,
		"shadowRadius": true,
		"shouldRasterizeIOS": true,
		"start": true,
		"style": {
			"alignContent": true,
			"alignItems": true,
			"alignSelf": true,
			"aspectRatio": true,
			"backfaceVisibility": true,
			"backgroundColor": {},
			"borderBottomColor": {},
			"borderBottomEndRadius": true,
			"borderBottomLeftRadius": true,
			"borderBottomRightRadius": true,
			"borderBottomStartRadius": true,
			"borderBottomWidth": true,
			"borderColor": {},
			"borderEndColor": {},
			"borderEndWidth": true,
			"borderLeftColor": {},
			"borderLeftWidth": true,
			"borderRadius": true,
			"borderRightColor": {},
			"borderRightWidth": true,
			"borderStartColor": {},
			"borderStartWidth": true,
			"borderStyle": true,
			"borderTopColor": {},
			"borderTopEndRadius": true,
			"borderTopLeftRadius": true,
			"borderTopRightRadius": true,
			"borderTopStartRadius": true,
			"borderTopWidth": true,
			"borderWidth": true,
			"bottom": true,
			"color": {},
			"decomposedMatrix": true,
			"direction": true,
			"display": true,
			"elevation": true,
			"end": true,
			"flex": true,
			"flexBasis": true,
			"flexDirection": true,
			"flexGrow": true,
			"flexShrink": true,
			"flexWrap": true,
			"fontFamily": true,
			"fontSize": true,
			"fontStyle": true,
			"fontVariant": true,
			"fontWeight": true,
			"height": true,
			"includeFontPadding": true,
			"justifyContent": true,
			"left": true,
			"letterSpacing": true,
			"lineHeight": true,
			"margin": true,
			"marginBottom": true,
			"marginEnd": true,
			"marginHorizontal": true,
			"marginLeft": true,
			"marginRight": true,
			"marginStart": true,
			"marginTop": true,
			"marginVertical": true,
			"maxHeight": true,
			"maxWidth": true,
			"minHeight": true,
			"minWidth": true,
			"opacity": true,
			"overflow": true,
			"overlayColor": {},
			"padding": true,
			"paddingBottom": true,
			"paddingEnd": true,
			"paddingHorizontal": true,
			"paddingLeft": true,
			"paddingRight": true,
			"paddingStart": true,
			"paddingTop": true,
			"paddingVertical": true,
			"position": true,
			"resizeMode": true,
			"right": true,
			"rotation": true,
			"scaleX": true,
			"scaleY": true,
			"shadowColor": {},
			"shadowOffset": {},
			"shadowOpacity": true,
			"shadowRadius": true,
			"start": true,
			"textAlign": true,
			"textAlignVertical": true,
			"textDecorationColor": {},
			"textDecorationLine": true,
			"textDecorationStyle": true,
			"textShadowColor": {},
			"textShadowOffset": true,
			"textShadowRadius": true,
			"textTransform": true,
			"tintColor": {},
			"top": true,
			"transform": {},
			"transformMatrix": true,
			"translateX": true,
			"translateY": true,
			"width": true,
			"writingDirection": true,
			"zIndex": true
		},
		"testID": true,
		"top": true,
		"transform": {},
		"translateX": true,
		"translateY": true,
		"width": true,
		"zIndex": true
	}
}